server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /api
  port: 8887

spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:file:./data/db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
